name: dpull  
paginate: 10 # pagination based on number of posts
paginate_path: "/page/:num"
permalink: "/blog/:title"
include: ["_static"]
exclude: ["README.md"] # files to exclude
pygments: true
encoding: utf-8
markdown: redcarpet
markdown_ext: md
redcarpet:
  extensions: ["tables"]

#excerpt_separator: <!--more--> 
excerpt_separator: ----------
