name: dpull  
about: 这家伙很懒，什么都没留下。
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
include: ["work/_static"]
exclude: ["README.md"] # files to exclude
pygments: true
encoding: utf-8
markdown: redcarpet
redcarpet: 
    extensions: ["tables"]

#excerpt_separator: <!--more--> 
excerpt_separator: ----------


urls:
    - text: email
      url: mailto:beingstudio@gmail.com
